packages:
  - examples/agent-demo
  - examples/filesystem
  - .

onlyBuiltDependencies:
  - "@biomejs/biome"
  - esbuild
  - lefthook
  - protobufjs

injectWorkspacePackages: true
strictPeerDependencies: true
